require: rubocop-rails

Rails/FilePath:
  Enabled: false

Layout/LineLength:
  Exclude:
    - "config/initializers/content_security_policy.rb"
    - "spec/services/card_image_loading_service_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Rails/Output:
  Enabled: false 