require: rubocop-rails

Rails/FilePath:
  Enabled: false

Layout/LineLength:
  Exclude:
    - "config/initializers/content_security_policy.rb"
    - "spec/services/card_image_loading_service_spec.rb"
    - "app/services/card_image_loading_service.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Rails/Output:
  Enabled: false 

Metrics/MethodLength:
  Exclude:
    - "app/services/card_image_loading_service.rb"
    - "app/services/guide_card_loading_service.rb"

Metrics/AbcSize:
  Exclude:
    - "app/services/guide_card_loading_service.rb"

Style/HashSyntax:
  EnforcedShorthandSyntax: never
